version: "3"
services:
  postgres:
    image: postgres:12.3-alpine
    restart: always
    networks:
      - fluxpm-test
    environment:
      POSTGRES_USER: fluxpm
      POSTGRES_PASSWORD: fluxpm_test
      POSTGRES_DB: fluxpm
    volumes:
      - fluxpm-postgres:/var/lib/postgresql/data
    ports:
      - 8865:5432
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
  redis:
    image: redis:6.2
    restart: always
    ports:
      - 6379:6379

volumes:
  fluxpm-postgres:
    external: false

networks:
  fluxpm-test:
    driver: bridge
