version: "3"
services:
  web:
    image: fluxpm/fluxpm:latest
    # build: .
    ports:
      - "6688:3333"
    depends_on:
      - postgres
    networks:
      - fluxpm-latest-test
    environment:
      FLUXPM_DATABASE_HOST: postgres
      FLUXPM_MIGRATE: "true"
  postgres:
    image: postgres:12.3-alpine
    restart: always
    networks:
      - fluxpm-latest-test
    environment:
      POSTGRES_USER: fluxpm
      POSTGRES_PASSWORD: fluxpm_test
      POSTGRES_DB: fluxpm
    volumes:
    - fluxpm-latest-postgres:/var/lib/postgresql/data

volumes:
  fluxpm-latest-postgres:
    external: false

networks:
  fluxpm-latest-test:
    driver: bridge
